name: mygithubwebpage
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.17
  go_router: ^6.0.1
  flutter_riverpod: ^2.1.3
  hooks_riverpod: ^2.1.3
  riverpod_annotation: ^1.1.1
  flutter_screenutil: ^5.6.0
  google_fonts: ^4.0.1
  getwidget: ^3.0.1
  animations: ^2.0.7
  responsive_builder: ^0.5.1
  flutter_markdown: ^0.6.14
  adaptive_theme: ^3.2.0
  font_awesome_flutter: ^10.4.0
  flutter_rounded_progress_bar: ^0.2.0
  url_launcher: ^6.1.10
  characters: ^1.2.1
  get_it: ^7.2.0
  dyn_mouse_scroll: ^1.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  riverpod_generator: ^1.1.1
  build_verify: ^3.1.0
  flutter_launcher_icons: ^0.12.0
  flutter_native_splash: ^2.2.18

flutter:
  uses-material-design: true

  fonts:
   - family: icomoon
     fonts:
      - asset: assets/fonts/icomoon.ttf

  assets:
    - assets/images/four.png
    - assets/images/three.png
    - assets/images/two.png
    - assets/images/one.png
    - assets/images/logos.png
    - assets/images/hkust.png
    - assets/icons/icon.png
    - assets/icons/icon2.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/icon.png"
    background_color: "#FFFFFF"
    # theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/icon.png"

flutter_native_splash:
  # flutter pub run flutter_native_splash:create
  # flutter pub run flutter_native_splash:remove

  color: "#FFFFFF"
  #background_image: "assets/background.png"
  image: assets/icons/icon.png 

  #branding: assets/dart.png
  #branding_mode: bottom

  #color_dark: "#042a49"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png
  #branding_dark: assets/dart_dark.png

  android_12:
    #image: assets/android12splash.png
    #color: "#42a5f5"
    #icon_background_color: "#111111"
    #branding: assets/dart.png
    #image_dark: assets/android12splash-invert.png
    #color_dark: "#042a49"
    #icon_background_color_dark: "#eeeeee"
  #android: false
  #ios: false
  #web: false
  #color_android: "#42a5f5"
  #color_dark_android: "#042a49"
  #color_ios: "#42a5f5"
  #color_dark_ios: "#042a49"
  #color_web: "#42a5f5"
  #color_dark_web: "#042a49"
  #image_android: assets/splash-android.png
  #image_dark_android: assets/splash-invert-android.png
  #image_ios: assets/splash-ios.png
  #image_dark_ios: assets/splash-invert-ios.png
  #image_web: assets/splash-web.png
  #image_dark_web: assets/splash-invert-web.png
  #background_image_android: "assets/background-android.png"
  #background_image_dark_android: "assets/dark-background-android.png"
  #background_image_ios: "assets/background-ios.png"
  #background_image_dark_ios: "assets/dark-background-ios.png"
  #background_image_web: "assets/background-web.png"
  #background_image_dark_web: "assets/dark-background-web.png"
  #branding_android: assets/brand-android.png
  #branding_dark_android: assets/dart_dark-android.png
  #branding_ios: assets/brand-ios.png
  #branding_dark_ios: assets/dart_dark-ios.png
  #android_gravity: center
  #ios_content_mode: center
  # web_image_mode can be one of the following modes: center, contain, stretch, and cover.
  #web_image_mode: center

  # The screen orientation can be set in Android with the android_screen_orientation parameter.
  # Valid parameters can be found here:
  # https://developer.android.com/guide/topics/manifest/activity-element#screen
  #android_screen_orientation: sensorLandscape
  #fullscreen: true

  # If you have changed the name(s) of your info.plist file(s), you can specify the filename(s)
  # with the info_plist_files parameter.  Remove only the # characters in the three lines below,
  # do not remove any spaces:
  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'