name: mygithubwebpage
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.17
  go_router: ^6.0.1
  flutter_riverpod: ^2.1.3
  hooks_riverpod: ^2.1.3
  riverpod_annotation: ^1.1.1
  flutter_screenutil: ^5.6.0
  google_fonts: ^4.0.1
  getwidget: ^3.0.1
  animations: ^2.0.7
  responsive_builder: ^0.5.1
  flutter_markdown: ^0.6.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  riverpod_generator: ^1.1.1
  build_verify: ^3.1.0
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true

  assets:
    - assets/
